http://catalog.data.gov/api/3/

// https://www.data.gov/developers/apis
// https://catalog.data.gov/dataset?q=-aapi+api+OR++res_format%3Aapi#topic=developers_navigation

###
https://dailymed.nlm.nih.gov/dailymed/webservices-help/v2/drugnames_api.cfm
